Add setting to optionally disable Cosmic's use of the Super key
pop-os/gnome-shell-extension-pop-cosmic pull request #183
Opened 2021-08-03 17:41 UTC by jmaargh

Closes #169

Currently, cosmic is quite opinionated about gnome's `overlay-key` setting. This PR adds a setting to entirely disable that behaviour. Obviously, this setting isn't exposed in the settings app, since that's in a different repo, but at least it provides the option.

I also took the liberty of running the formatter on the JS file I touched, changes in a separate commit so I can easily revert if this isn't desired.

2021-08-03 18:54 UTC, jacobgkau commented
Testing this, it appears to have the same behavior as just changing the super key setting to Workspaces. After setting `disable-overlay-key` to `true`, the `Super Key Action` setting is disregarded and the super key opens the Workspaces menu. Workspaces is still separate from Applications.

@jmaargh I understand you're doing this because you have another extension trying to use the Super key, can you provide an example of an extension that would utilize this?

2021-08-03 19:06 UTC, jmaargh commented
> @jmaargh I understand you're doing this because you have another extension trying to use the Super key, can you provide an example of an extension that would utilize this?

Personally, I'm using ArcMenu, but the same principle would apply to anything else which may want to bind to the super key (e.g. another launcher).

2021-08-03 19:25 UTC, jacobgkau commented
OK, with `disbale-overlay-key` set to `false`, I see the conflict between ArcMenu and COSMIC's menus when trying to use the Super key. (For Workspaces/Activities, the menu opens at the same time as ArcMenu; for the Launcher, either the Launcher opens on the first press and ArcMenu opens on the next press, or neither opens.) When I set `disable-overlay-key` to `true`, ArcMenu is able to open/close with the Super key as I would expect.

If I perform the following sequence:

- Set `disable-overlay-key` to `true`
- Change `Super Key Action` to `Workspaces`
- Set `disable-overlay-key` to `false`
- Change `Super Key Action` to `Launcher`

Then the super key doesn't work until I restart GNOME Shell.

- Workspaces and Applications don't seem to require restarting GNOME Shell after this option is changed, only Launcher.
- The Launcher only requires the restart if it's not the active option when the `disable-overlay-key` is turned off.

Is this inconsistent behavior expected? It wouldn't be critical for a hidden gsetting, but it would be a blocker for adding this to the GUI settings.

2021-08-03 21:30 UTC, jmaargh commented
> If I perform the following sequence:
> 
>     * Set `disable-overlay-key` to `true`
> 
>     * Change `Super Key Action` to `Workspaces`
> 
>     * Set `disable-overlay-key` to `false`
> 
>     * Change `Super Key Action` to `Launcher`
> 
> 
> Then the super key doesn't work until I restart GNOME Shell.
> 
>     * Workspaces and Applications don't seem to require restarting GNOME Shell after this option is changed, only Launcher.
> 
>     * The Launcher only requires the restart if it's not the active option when the `disable-overlay-key` is turned off.

Nice catch. I was able to reproduce this behaviour and have pushed a fix. Now the code only dis/connects the overlay key handler when the new setting is changed, before I incorrectly assumed that behaviour was idempotent.

> Is this inconsistent behavior expected? It wouldn't be critical for a hidden gsetting, but it would be a blocker for adding this to the GUI settings.

I don't suppose it would be, but it should be fixed now nonetheless.

2021-08-04 14:51 UTC, jacobgkau approved these changes
Turning the setting on/off is now working as expected, I'm not seeing any problems with including this from a usability perspective (the default setting is the same as current behavior.) 

Implementation into the GUI will probably need UX consultation (I could see it being a "do nothing" option in the `Super Key Action` list or being a separate on/off switch.)

2021-08-04 15:22 UTC, ids1024 commented
>Implementation into the GUI will probably need UX consultation (I could see it being a "do nothing" option in the Super Key Action list or being a separate on/off switch.)

It seems like it would be strange to expose it as a separate option in the GUI if this is indistinguishable from setting it to "Workspaces" , except in the presence of another extension.

I suppose it could just behave this way when set to Workspaces, instead of having a separate setting?

If the behavior is slightly different, or may be different in the future, I guess a separate gsetting makes sense, though I don't know if it should be exposed in the UI.

2021-08-04 15:41 UTC, jacobgkau commented
> It seems like it would be strange to expose it as a separate option in the GUI if this is indistinguishable from setting it to "Workspaces" , except in the presence of another extension.

You're 100% right that "do nothing" in the list wouldn't make sense in the GUI since it will still do something by default.

> I suppose it could just behave this way when set to Workspaces, instead of having a separate setting?

That seems like it might make sense. Just off the top of my head, I don't think there would be a case when a user wants COSMIC to conflict with their other extension.

It would still require that users know Workspaces is the magic setting to use when they want another extension to take over the Super key, though. Not sure if something about "this choice allows other extensions to use the Super key" would fit in the copy or not.

> If the behavior is slightly different, or may be different in the future, I guess a separate gsetting makes sense, though I don't know if it should be exposed in the UI.

If we don't want to expose this at all in the GUI, that's fine. This is why we'd want UX involved if we did that. The setting is logical to people who know what it does, but would be irrelevant to normal users using only the default COSMIC desktop/extensions. On the other hand, I don't know if the majority of people attempting to use third-party extensions will know to check for hidden gsettings if we don't expose it.

2021-08-04 15:52 UTC, jmaargh commented
> If we don't want to expose this at all in the GUI, that's fine. This is why we'd want UX involved if we did that. The setting is logical to people who know what it does, but would be irrelevant to normal users using only the default COSMIC desktop/extensions. On the other hand, I don't know if the majority of people attempting to use third-party extensions will know to check for hidden gsettings if we don't expose it.

Perhaps unsurprisingly, I'm happy just having the option, wherever it is, and leaving the "discoverability" be by people being told on forums.

However, another option is to have this flag in the extension's settings page, which is currently empty and simply redirects you to the settings app. Seems like an option for such niche settings, especially as the use-case is for people who are already installing and configuring extensions, presumably using gnome tweaks (this is the first place I went to look for this option, for example).

2021-08-04 18:17 UTC, jmaargh commented
> However, another option is to have this flag in the extension's settings page, which is currently empty and simply redirects you to the settings app. Seems like an option for such niche settings, especially as the use-case is for people who are already installing and configuring extensions, presumably using gnome tweaks (this is the first place I went to look for this option, for example).

I went ahead and implemented this, can easily revert if it's not wanted.

2021-08-04 18:24 UTC, jacobgkau requested changes
This doesn't seem to be showing up after pulling and rebuilding:

![Screenshot from 2021-08-04 12-20-58](https://user-images.githubusercontent.com/7199422/128234301-dfd07d4f-9b20-4768-95fe-5d81bf95efda.png)

2021-08-04 18:24 UTC, jacobgkau commented on prefs.js
> +        label: "<b>Niche Settings</b>",
I don't think `Niche Settings` is a sensible label. It doesn't mean anything with relation to what the settings will do.

2021-08-04 18:27 UTC, jacobgkau commented
Also, after the last changes, after restarting the shell, the setting acts as if it's set to `true` until I toggle to `true` and then back to `false`.

2021-08-04 18:28 UTC, jacobgkau commented on prefs.js
> +        label: "Disable super key action (reverts to gnome default)",
If this label was going to be present, GNOME would need to be capitalized. We also typically capitalize `Super key` in copy.

2021-08-04 18:40 UTC, jmaargh commented on prefs.js
> +        label: "Disable super key action (reverts to gnome default)",
fixed

2021-08-04 18:41 UTC, jacobgkau commented
@maria-komarova Do you have thoughts about putting advanced settings into the Extensions settings panel, or, more broadly, where this option would fit, if anywhere?

I personally buy this justification to have it in Extensions rather than the Settings app, if we don't think it will fit in Settings:

> the use-case is for people who are already installing and configuring extensions

Right now, it's underneath the `Configure in Settings` button (see below.)

2021-08-04 18:41 UTC, jmaargh commented on prefs.js
> +        label: "<b>Niche Settings</b>",
I've changed to "Advanced". I'm very unopinionated on how any of this copy should read, so feel free to dictate any changes you'd like.

2021-08-04 18:41 UTC, jmaargh commented
> Also, after the last changes, after restarting the shell, the setting acts as if it's set to `true` until I toggle to `true` and then back to `false`.

Fixed

2021-08-04 18:43 UTC, jacobgkau commented
Here's what it looks like after the obvious copy fixes:

![Screenshot from 2021-08-04 12-42-34](https://user-images.githubusercontent.com/7199422/128236945-145ebd48-8bb1-49fc-84c1-86c812104370.png)

2021-08-04 18:45 UTC, jacobgkau commented on prefs.js
> +        label: "<b>Niche Settings</b>",
Fixed in https://github.com/pop-os/cosmic/pull/183/commits/bc95be0445eef490166697af73e3e3ce6ac094db.

2021-08-04 18:45 UTC, jacobgkau commented on prefs.js
> +        label: "Disable super key action (reverts to gnome default)",
Fixed in https://github.com/pop-os/cosmic/pull/183/commits/bc95be0445eef490166697af73e3e3ce6ac094db.

2021-08-04 20:40 UTC, maria-komarova commented
I'm trying to think of a better place where this setting could live but it is a somewhat tricky one. To a degree it might make sense to have it in Settings with something like "Reserve Super Key for Actions other than Default". But that still seems somewhat weird since this is not strictly Disable the Super key. That makes me wonder if we should have two things - Disable Super key option in the GCC, and "Allow using the Super key by extensions" in this Extensions dialog. 
The reason why it seems to me that the toggle in the dialog is not such a good idea is because the change won't be reflected in the Settings app. I know that if one toggles Super key in the extensions dialog the expectation is that it was intentional. But it introduces a certain inconsistency into the settings.

2021-08-05 10:59 UTC, jmaargh commented
Like I said, I'd be happy with it being a hidden option, if that's what gets this merged.

After thinking about this for a bit, I really don't think that having this as an option in Settings is a good idea at all. It's fundamentally an option that relates to cosmic being a gnome extension, which is a nuance that doesn't make much sense to try and explain in the main settings.

As for the change in the extension preferences dialog not being reflected in Settings, does that matter? This is super common when customising gnome with extensions that you end up with options in Settings that no longer behave as advertised and this option is only really relevant if you're doing such customisation. In theory you could grey out the option in Settings and insert a message saying this has been disabled in the extension, but that feels like overkill for a niche little option like this.

2021-08-05 19:17 UTC, jacobgkau commented
> This is super common when customising gnome with extensions that you end up with options in Settings that no longer behave as advertised

While you're correct that this is common in GNOME-based distributions, Pop!_OS is supposed to be a cohesive operating system, so our standards are a little higher. We don't want the possibility of a user getting confused or stuck should they find their way into the advanced settings and later forget that they changed the option there. The Super key is a core part of the user experience, and the core settings should always work and be accurate.

---

After speaking with @maria-komarova, we'd like to try this:

In the Extensions panel (advanced settings):

- Rename the new option to `Disable Super key override`.
- Add a description underneath the option:
```
Super will open Workspaces unless behavior is specified by other extensions
```
- We'd also like to left-align the `Advanced Settings` header and adjust the spacing slightly, here is a mockup that Maria made:

![Pop-Cosmic-extension-dialog (1)](https://user-images.githubusercontent.com/7199422/128407354-f869ccf8-5155-45e6-afe9-d98998ce7355.png)

In GNOME Control Center/desktop-widget:

- When the `Disable Super key override` setting is enabled, the `Super Key Action` section should have no bullet points activated, but should remain selectable (not greyed out), similar to what happens with the `Dock Size` setting when using a custom size.
- When the `Disable Super key override` setting is enabled, display the following message after the `Super Key Action` header and before the three bullet-point options:
```
Super key override was disabled via advanced settings.
  - Super will open Workspaces unless behavior is specified by other extensions.
  - Selecting an option below will re-enable the override.
```
- When the user selects one of the bullet points in `Super Key Action`, the message is hidden and the `Disable Super key override` setting is turned off.

2021-08-06 08:08 UTC, jmaargh commented
That all works for me. I can implement the changes here (though if you have the UI file for that mockup, that would be helpful). Obviously changes to settings will have to be in https://github.com/pop-os/gnome-control-center

2021-08-06 15:37 UTC, maria-komarova commented
@jmaargh I don't have a UI file for this mockup since that was a quick visual reference for the spacing and alignment rather than the detailed mockup. I'd say vertical padding between the header bar and the first copy at the top is 2x the padding between this copy and the button "Configure in Settings". The padding between the button and the divider line is also 2x the padding between this copy and the button "Configure in Settings".

2021-08-08 11:55 UTC, jmaargh commented
I've updated the preferences widget to match the given design

2021-08-09 20:58 UTC, jacobgkau commented
Hmm, I'm getting this output when I try to open the COSMIC settings panel now (after launching `gnome-extensions-app` from a terminal):

```
Gjs-Message: 14:54:57.988: JS LOG: Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

I get this in journalctl:

```
Aug 09 14:56:25 pop-os dbus-daemon[2144]: [session uid=1000 pid=2144] Activating service name='org.gnome.Shell.Extensions' requested by ':1.95' (uid=1000 pid=3881 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Exte" label="unconfined")
Aug 09 14:56:25 pop-os dbus-daemon[2144]: [session uid=1000 pid=2144] Successfully activated service 'org.gnome.Shell.Extensions'
Aug 09 14:56:25 pop-os gjs[4210]: failed to add UI: Failed to open file “/usr/share/gnome-shell/extensions/pop-cosmic@system76.com/prefs.ui”: No such file or directory
Aug 09 14:56:25 pop-os kernel: traps: gjs[4210] trap int3 ip:7f15f99c0647 sp:7fffba610a00 error:0 in libglib-2.0.so.0.6800.1[7f15f997d000+8d000]
```

2021-08-09 22:17 UTC, jmaargh commented
@jacobgkau sorry, forgot to add ui file to Makefile, should be good now

2021-08-10 14:38 UTC, jacobgkau commented
Looks great now!

![Screenshot from 2021-08-10 08-36-06](https://user-images.githubusercontent.com/7199422/128886609-6da85d88-fee4-4bf1-b72a-d6b029ae11e7.png)

I believe the corresponding Settings changes (for you or whoever else will be doing it) will need to be in the desktop-widget repo, which provides the entire Desktop category of settings: https://github.com/pop-os/desktop-widget

2021-08-10 21:39 UTC, jmaargh commented
I also implemented the required changes to the GCC widget: https://github.com/pop-os/desktop-widget/pull/55

![image](https://user-images.githubusercontent.com/11151181/128938652-730d8b32-7754-4f53-bb2b-422ce32dd96e.png)

2021-08-11 18:25 UTC, jacobgkau commented
@jmaargh The desktop-widget side is looking great! However, the option to disable the override no longer seems to be working. (It shows the message in desktop-widget, but the Super key still opens the Launcher or Applications menu, whatever it was set to last.)

2021-08-11 18:27 UTC, jacobgkau commented
Ah, one other thing I noticed, if I disable the override from the Extensions app settings, the message in desktop-widget goes away, but the appropriate bullet point in desktop-widget isn't reselected.

2021-08-11 18:47 UTC, jacobgkau commented
Hmm, the first issue wasn't occurring on a second machine, and now it's not happening on the first one either. The second issue with the bullet points remaining unselected is still happening on both.

2021-08-11 21:14 UTC, jmaargh commented
@jacobgkau The correct radio button should now become re-selected when the `disable-overlay-key` option goes false.

As for your other machine where the disable wasn't working, could you verify a couple of things for me?

1. The `extension.js` file is installed and shares a hash with the one from source
2. The `disable-overlay-key` has been added to the gsettings schema (e.g., does it appear in dconf editor?)

2021-08-12 20:22 UTC, jacobgkau approved these changes
I was only able to recreate the disable not working issue once, and it was when I didn't restart GNOME Shell after updating. I have to assume that's what happened the first time.

All behavior here is working how I'd expect. I've tried various sequences of disabling/enabling the override and switching the action setting, and have not been able to break anything. I confirmed on a fresh machine that installing the update does not change any default settings.

2021-08-16 16:33 UTC, ids1024 approved these changes
Looks good. The prefs code doesn't work on Gnome 40 (since that uses gtk4 for prefs), but that seems to already be broken, so not really a regression.

2021-08-18 15:01 UTC, merged

2021-08-19 13:59 UTC, ids1024 commented
This may have caused an inconsistent bug in super key behavior: https://github.com/pop-os/cosmic/issues/195