Fix bug in #183
pop-os/gnome-shell-extension-pop-cosmic pull request #197
Opened 2021-08-23 20:37 UTC by jmaargh

Fix bug in PR #183 as found in #195

The issue was that an enable/disable cycle without restarting the shell was not a no-op. I didn't consider that state (in particular, `overlay_key_action` in this case, which is also used as the flag for whether or not the overlay key is disabled) would remain.

To fix this, I've moved the logic of setting `overlay_key_action` into the `dis/connect_overlay_key_handler` functions, so that state always stays in sync with whether or not the handler is actually connected.

It has fixed the issue in my testing locking/unlocking.

2021-08-30 14:55 UTC, jacobgkau approved these changes
I've tested this fairly extensively on a test machine as well as my primary machine, over a period of several days. I can confirm the lock/unlock case is now fixed, and I have not been able to create any other cases where the Super key stops working, either.

2021-08-30 18:25 UTC, jackpot51 approved these changes
Thanks for finding the issue! This looks good to me

2021-08-30 18:26 UTC, jackpot51 commented
It looks like this PR will need to rebased on the latest master_hirsute prior to merging

2021-09-01 13:47 UTC, jmaargh commented
Rebase done, should be good to merge now

2021-09-01 14:02 UTC, jackpot51 approved these changes

2021-09-01 14:02 UTC, jackpot51 commented
@jacobgkau do you want to give this one more quick look through to make sure the rebase was okay, and then I will merge?

2021-09-01 15:23 UTC, jacobgkau requested changes
Hold on, I'm now seeing that the Super Key Action setting in Settings -> Desktop isn't working. If the override is disabled, then Super always opens the Launcher.

2021-09-01 19:59 UTC, jmaargh commented
@jacobgkau good catch, should be fixed now

2021-09-13 13:48 UTC, jacobgkau approved these changes
This is now working as expected, still not seeing any side effects with the latest fixes.

2021-09-13 13:49 UTC, merged