Make app grid always 7 by 3
pop-os/gnome-shell-extension-pop-cosmic pull request #306
Opened 2022-02-03 19:34 UTC by jacobgkau

Fixes #305.

This calculates the app grid's width & height by multiplying the actual size of the icons (168px * scale) by the number of icons we want to display. (Previously, the grid was calculated as a proportion of the display's size, which resulted in inconsistent numbers of icons being displayed on differently-sized/shaped displays.)

I removed pointless CSS settings for the width & height since they weren't being used anyway, since the dynamic calculation already took precedence. I left the class there since there were already some empty classes in the file, and added a note about the dynamic calculation to assist future troubleshooting.

Needs testing on HiDPI & ultrawide displays.

2022-02-03 19:36 UTC, jacobgkau commented
On second thought, probably need to still use proportion of the display _if_ that would result in a smaller width/height, otherwise it will overflow on displays where 7 icons won't fit. Also need to clarify expected height behavior.

2022-02-03 19:52 UTC, ids1024 commented
> Needs testing on HiDPI & ultrawide displays.

It should be tested at 720p/768p to make sure it doesn't regress the behavior there either.

2022-02-03 20:40 UTC, jacobgkau commented
1080p landscape:
![Screenshot from 2022-02-03 13-36-35](https://user-images.githubusercontent.com/7199422/152425020-5c9b4237-7196-4004-8c72-a9e5bdc02d78.png)

1080p portrait:
![Screenshot from 2022-02-03 13-35-59](https://user-images.githubusercontent.com/7199422/152425025-cdce7690-3a8a-43dc-bcf6-fde7c742d0a7.png)

720p landscape:
![Screenshot from 2022-02-03 13-36-24](https://user-images.githubusercontent.com/7199422/152425023-fc806948-58b3-46d6-b043-f89d3e186ad6.png)

Still needs testing on HiDPI & ultrawide displays.

2022-02-04 00:38 UTC, 13r0ck approved these changes, later dismissed
I am in favor of this being a dconf value so that users can choose if they like the old way or the new one (or even if they would prefer values other than 7 x 3).

This functions as intended

2022-02-04 17:20 UTC, ids1024 requested changes
This doesn't seem to scale correctly at 4k 2x. It seems simple to fix though.

2022-02-04 17:20 UTC, ids1024 commented on applications.js
> +        const height = Math.min(Math.floor(monitorScale * 168) * 3,
This should be just be `168`, not `Math.floor(monitorScale * 168)`. Pixel sizes are already scaled, except for `monitor.width`/`monitor.width`.

2022-02-04 17:20 UTC, ids1024 commented on applications.js
> +        const width = Math.min(Math.ceil(monitorScale * 168) * 7,
Likewise, `Math.ceil(monitorScale * 168)` should just be `168`.

2022-02-07 17:10 UTC, jacobgkau commented
I have an addw2 for testing now and confirmed this was not working as intended on a 4K scaled screen (not sure what @13r0ck was using to test HiDPI before):

![Screenshot from 2022-02-07 09-21-37](https://user-images.githubusercontent.com/7199422/152835388-afadd41f-9a5b-4ed2-adb6-f183216dbae8.png)

Implemented the suggested changes by @ids1024, now it is working on addw2:

![Screenshot from 2022-02-07 09-59-31](https://user-images.githubusercontent.com/7199422/152835394-0450ff52-b55d-443b-aeaf-ca4e1b71411a.png)

Still works as intended on LoDPI, and on both of these systems turned to portrait orientation.

When connecting a HiDPI system to a LoDPI external display and attempting to use GNOME Shell's fractional scaling to set the external display's scale differently from the internal display, I'm seeing some inconsistency in the scale of the library on the external display, but still no more than the maximum number of icons being displayed. This doesn't happen when the HiDPI daemon is running (although it's currently [broken in Hybrid mode](https://github.com/pop-os/hidpi-daemon/issues/34).)

2022-02-07 17:22 UTC, ids1024 approved these changes

2022-02-08 19:06 UTC, 13r0ck approved these changes

2022-02-08 19:25 UTC, merged