fix: Exception when cosmicDock.stateObj.dockManager may be undefined
pop-os/gnome-shell-extension-pop-cosmic pull request #362
Opened 2022-09-27 18:41 UTC by mmstick

Issue was reported here https://chat.pop-os.org/pop-os/pl/ttud6b16rt8qxrsz9w16xf38rc

There's a possibility that the `dockManager` field in the cosmic dock extension may be undefined. We should check if the field exists to prevent an exception from breaking things in cosmic.

2022-09-27 19:33 UTC, jackpot51 submitted a review, later dismissed

2022-09-27 20:01 UTC, 13r0ck requested changes

2022-09-27 20:01 UTC, 13r0ck commented on applications.js
> +            const dockManager = cosmicDock.stateObj.dockManager
Under some circumstances `stateObj` can also be null. https://github.com/pop-os/cosmic-workspaces/blob/master_jammy/util.js#L67 checks for it. We should probably do that here too.

2022-09-27 20:08 UTC, 13r0ck approved these changes

2022-09-28 00:26 UTC, jacobgkau approved these changes
Confirmed the issue from Mattermost after installing Dash to Dock. Confirmed this fix resolves that issue. No regressions on a system without Dash to Dock (with or without COSMIC Dock enabled.)

2022-09-28 13:24 UTC, merged